# https://travis-ci.org/tornadoweb/tornado

dist: xenial
language: python
addons:
  apt:
    packages:
      - libgnutls-dev
      - patchelf

# For a list of available versions,run
#     aws s3 ls s3://travis-python-archives/binaries/ubuntu/16.04/x86_64/
jobs:
  fast_finish: true
  include:
    # 3.5.2 is interesting because it's the version in ubuntu 16.04, and due to python's
    # "provisional feature" rules there are significant differences between patch
    # versions for asyncio and typing.
    - python: 3.5.2
      # Twisted doesn't install on python 3.5.2, so don't run the "full" tests.
      env: TOX_ENV=py35
    - python: '3.5'
      services: docker
      env: TOX_ENV=py35-full BUILD_WHEEL=1 CIBW_BUILD=cp35-manylinux_x86_64 CIBW_TEST_REQUIRES="tox && yum install -y libcurl-devel openssl-devel" CIBW_TEST_COMMAND="cd {project} && tox -e py35-full"
    - python: '3.5'
      arch: arm64
      services: docker
      env: TOX_ENV=py35-full BUILD_WHEEL=1 PIP_NO_CACHE_DIR=off PYCURL_SSL_LIBRARY=nss CIBW_BUILD=cp35-manylinux_aarch64 CIBW_TEST_REQUIRES="tox && yum install -y libcurl-devel openssl-devel" CIBW_TEST_COMMAND="cd {project} && tox -e py35-full"
    - python: '3.6'
      services: docker
      env: TOX_ENV=py36-full BUILD_WHEEL=1 CIBW_BUILD=cp36-manylinux_x86_64 CIBW_TEST_REQUIRES="tox" CIBW_BEFORE_ALL_LINUX="yum install -y libcurl-devel openssl-devel" CIBW_TEST_COMMAND="cd {project} && tox -e py36-full"
    - python: '3.6'
      arch: arm64
      services: docker
      env: TOX_ENV=py36-full BUILD_WHEEL=1 PIP_NO_CACHE_DIR=off PYCURL_SSL_LIBRARY=nss CIBW_BUILD=cp36-manylinux_aarch64 CIBW_BEFORE_ALL_LINUX="yum install -y libcurl-devel openssl-devel" CIBW_TEST_REQUIRES="tox" CIBW_TEST_COMMAND="cd {project} && tox -e py36-full"
    - python: '3.7'
      services: docker
      env: TOX_ENV=py37-full BUILD_WHEEL=1 CIBW_BUILD=cp37-manylinux_x86_64 CIBW_TEST_REQUIRES="tox" CIBW_BEFORE_ALL_LINUX="yum install -y libcurl-devel openssl-devel" CIBW_TEST_COMMAND="cd {project} && tox -e py37-full"
    - python: '3.7'
      arch: arm64
      services: docker
      env: TOX_ENV=py37-full BUILD_WHEEL=1 PIP_NO_CACHE_DIR=off PYCURL_SSL_LIBRARY=nss CIBW_BUILD=cp37-manylinux_aarch64 CIBW_BEFORE_ALL_LINUX="yum install -y libcurl-devel openssl-devel" CIBW_TEST_REQUIRES="tox" CIBW_TEST_COMMAND="cd {project} && tox -e py37-full"
    - python: '3.8'
      services: docker
      env: TOX_ENV=py38-full BUILD_WHEEL=1 CIBW_BUILD=cp38-manylinux_x86_64 CIBW_TEST_REQUIRES="tox && yum install -y libcurl-devel openssl-devel" CIBW_TEST_COMMAND="cd {project} && tox -e py38-full"
    - python: '3.8'
      arch: arm64
      services: docker
      env: TOX_ENV=py38-full BUILD_WHEEL=1 PIP_NO_CACHE_DIR=off PYCURL_SSL_LIBRARY=nss CIBW_BUILD=cp38-manylinux_aarch64 CIBW_TEST_REQUIRES="tox && yum install -y libcurl-devel openssl-devel" CIBW_TEST_COMMAND="cd {project} && tox -e py38-full"
    - python: pypy3.5-5.10.1
      # Pypy is a lot slower due to jit warmup costs, so don't run the "full"
      # test config there.
      env: TOX_ENV=pypy3
    - python: nightly
      env: TOX_ENV=py3-full
      # Docs and lint python versions must be synced with those in tox.ini
    - python: '3.8'
      env: TOX_ENV=docs
    - python: '3.8'
      arch: arm64
      env: TOX_ENV=docs
    - python: '3.8'
      env: TOX_ENV=lint
  allow_failures:
    # Currently failing due to https://foss.heptapod.net/pypy/cffi/issues/458
    - python: nightly

install:
    - |
      if [[ -n ${BUILD_WHEEL} ]]; then
         pwd
         pwd
         ls
         ls
         pip install -U cibuildwheel
         cibuildwheel --output-dir wheelhouse
         pwd
         pwd
         pwd
         ls wheelhouse
      fi
    - travis_retry pip install tox
    - python -VV
    - curl-config --version; pip freeze
script:
    - "tox -e $TOX_ENV -- $TOX_ARGS"
